version: '3'
services:

  redis:
    image: redis
    ports:
      - 6379:6379

  redis-proxy:
    build:
      context: .
    links:
      - redis
    ports:
      - 9000:9000
    command: redis-proxy
