version: '3'
services:
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
  proxy:
    build: .
    container_name: proxy
    ports:
      - "9000:9000"
    links:
      - redis
