version: '3'
services:

  redis:
    image: redis
    ports:
      - 6379:6379

  redis_proxy_tests:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile.test
    links:
      - redis
    ports:
      - 9000:9000
    volumes:
      - $PWD:/go/src/github.com/manojankitha/redis-proxy
